name: ParEM
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - notebook=6.4.5
  - numpy=1.20.3
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - keras=2.8.0
  - jax=0.2.27
  - jaxlib=0.1.75
  - python-wget=3.2

